# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Collect all the Python files
a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app.py', '.'),
        ('config.py', '.'),
        ('pdf_processor.py', '.'),
        ('llm_agent.py', '.'),
        ('translation_service.py', '.'),
        ('presentation_builder.py', '.'),
        ('main_processor.py', '.'),
        ('test_setup.py', '.'),
        ('README.md', '.'),
        ('SETUP_GUIDE.md', '.'),
        ('.env', '.'),
        ('example', 'example'),
    ],
    hiddenimports=[
        'streamlit',
        'langchain',
        'langchain_openai',
        'langchain_core',
        'langchain_community',
        'azure.ai.translation.text',
        'openai',
        'python_pptx',
        'PyPDF2',
        'fitz',
        'PIL',
        'dotenv',
        'requests',
        'beautifulsoup4',
        'lxml',
        'pandas',
        'numpy',
        'altair',
        'pydeck',
        'watchdog',
        'gitpython',
        'rich',
        'click',
        'tornado',
        'jinja2',
        'markupsafe',
        'pyyaml',
        'sqlalchemy',
        'aiohttp',
        'dataclasses_json',
        'jsonpatch',
        'langsmith',
        'pydantic',
        'tiktoken',
        'isodate',
        'azure_core',
        'xlsxwriter',
        'pymupdfb',
        'charset_normalizer',
        'idna',
        'urllib3',
        'certifi',
        'soupsieve',
        'anyio',
        'distro',
        'httpx',
        'jiter',
        'sniffio',
        'tqdm',
        'aiohappyeyeballs',
        'aiosignal',
        'attrs',
        'frozenlist',
        'multidict',
        'propcache',
        'yarl',
        'jsonschema',
        'narwhals',
        'six',
        'colorama',
        'marshmallow',
        'typing_inspect',
        'gitdb',
        'httpcore',
        'h11',
        'zipp',
        'jsonpointer',
        'markdown_it_py',
        'pygments',
        'greenlet',
        'regex',
        'smmap',
        'markupsafe',
        'jsonschema_specifications',
        'referencing',
        'rpds_py',
        'mdurl',
        'mypy_extensions',
        'streamlit.runtime.scriptrunner.magic_funcs',
        'streamlit.runtime.scriptrunner.script_runner',
        'streamlit.runtime.stats',
        'streamlit.runtime.streaming_server',
        'streamlit.runtime.websocket_connection_manager',
        'streamlit.runtime.websocket_server',
        'streamlit.runtime.websocket_session_manager',
        'streamlit.runtime.websocket_util',
        'streamlit.runtime.websocket_websocket_connection',
        'streamlit.runtime.websocket_websocket_server',
        'streamlit.runtime.websocket_websocket_session_manager',
        'streamlit.runtime.websocket_websocket_util',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PDF_to_Presentation_Converter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
